# Generated by Django 3.1.7 on 2021-04-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_profile_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='key',
            field=models.BinaryField(blank=True, default=b''),
        ),
    ]
