# Generated by Django 3.1.7 on 2021-04-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210406_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.BinaryField(blank=True, default=b'Expense'),
        ),
        migrations.AlterField(
            model_name='income',
            name='description',
            field=models.BinaryField(blank=True, default=b'Income'),
        ),
    ]
