# Generated by Django 3.1.7 on 2021-04-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210406_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.BinaryField(blank=True, default=b'amount'),
        ),
    ]
