# Generated by Django 3.1.7 on 2021-04-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210406_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.TextField(blank=True, default='light'),
        ),
    ]
