# Generated by Django 3.1.7 on 2021-04-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_profile_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.TextField(blank=True, default='null'),
        ),
    ]
